In [1]:
import numpy as np

a = np.array([1, 2, 3])

In [2]:
store_a = [20, 10, 30]  
store_b = [70, 90, 70]

In [3]:
list_sum = store_a + store_b 
list_sum

[20, 10, 30, 70, 90, 70]

In [ ]:
np_store_a = np.array(store_a)  
np_store_b = np.array(store_b)

In [ ]:
array_sum = np_store_a + np_store_b
array_sum

array([ 90, 100, 100])

In [ ]:
a = np.array([2, 3, 4]) # 넘파이 ndarray 객체의 생성

a.shape, a.ndim, a.dtype, a.itemsize, a.size

((3,), 1, dtype('int64'), 8, 3)

In [ ]:
a = np.array([10, 20, 30])   
b = np.array([1, 2, 3])
a + b

array([11, 22, 33])

In [8]:
a - b

array([ 9, 18, 27])

In [9]:
a * b

array([10, 40, 90])

In [10]:
a / b

array([10., 10., 10.])

In [14]:
a = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ]
)

a.shape, a.ndim, 

((2, 4), 2)

In [15]:
a = np.array([1, 2, 3, 4], dtype = np.int32)

In [16]:
a = np.array([1, 2, 3, 4], dtype = 'int32')

In [17]:
a = np.array([10, 20, 30])
a * 10

array([100, 200, 300])

In [20]:
a + 10

array([20, 30, 40])

In [21]:
b = np.array([[10, 20, 30],
              [40, 50, 60]])
c = np.array([2, 3, 4])
b + c

array([[12, 23, 34],
       [42, 53, 64]])

In [22]:
b * c

array([[ 20,  60, 120],
       [ 80, 150, 240]])

In [23]:
a = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12]
    ]
)

b = np.array([[1, 2, 3]])

addition_result = a + b

multiplication_result = a * b

addition_result, multiplication_result


(array([[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12],
        [11, 13, 15]]),
 array([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27],
        [10, 22, 36]]))

In [24]:
np.zeros((2, 3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.full((2, 3), 100)

array([[100, 100, 100],
       [100, 100, 100]])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [32]:
np.arange(0.0, 1.0, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [33]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [36]:
a = np.logspace(0, 5, 6).round(10)
a                                 

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [37]:
np.log10(a)

array([0., 1., 2., 3., 4., 5.])

In [38]:
angles = np.linspace(0, np.pi, 100)

sin_values = np.sin(angles)

sin_values

array([0.00000000e+00, 3.17279335e-02, 6.34239197e-02, 9.50560433e-02,
       1.26592454e-01, 1.58001396e-01, 1.89251244e-01, 2.20310533e-01,
       2.51147987e-01, 2.81732557e-01, 3.12033446e-01, 3.42020143e-01,
       3.71662456e-01, 4.00930535e-01, 4.29794912e-01, 4.58226522e-01,
       4.86196736e-01, 5.13677392e-01, 5.40640817e-01, 5.67059864e-01,
       5.92907929e-01, 6.18158986e-01, 6.42787610e-01, 6.66769001e-01,
       6.90079011e-01, 7.12694171e-01, 7.34591709e-01, 7.55749574e-01,
       7.76146464e-01, 7.95761841e-01, 8.14575952e-01, 8.32569855e-01,
       8.49725430e-01, 8.66025404e-01, 8.81453363e-01, 8.95993774e-01,
       9.09631995e-01, 9.22354294e-01, 9.34147860e-01, 9.45000819e-01,
       9.54902241e-01, 9.63842159e-01, 9.71811568e-01, 9.78802446e-01,
       9.84807753e-01, 9.89821442e-01, 9.93838464e-01, 9.96854776e-01,
       9.98867339e-01, 9.99874128e-01, 9.99874128e-01, 9.98867339e-01,
       9.96854776e-01, 9.93838464e-01, 9.89821442e-01, 9.84807753e-01,
      

In [43]:
a = np.array([1, 3, 4])
np.insert(a, 1, 2)

array([1, 2, 3, 4])

In [ ]:
b = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(b, 1, 4, axis = 0)

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

In [50]:
np.insert(b, 1, 4, axis = 1)

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]])

In [52]:
c = np.array([[1, 2, 3], [4, 5, 6]])
np.flip(c, axis=1)

array([[3, 2, 1],
       [6, 5, 4]])

In [53]:
np.flip(c, axis=0)

array([[4, 5, 6],
       [1, 2, 3]])

In [56]:
a = np.array( 
    [
        [1, 2, 3], 
        [4, 5, 6],
        [7, 8, 9], 
        [0, 1, 2]
    ] 
)

print(a[0][0])
print(a[2])

1
[7 8 9]


In [55]:
a[1:][0:2]

array([[4, 5, 6],
       [7, 8, 9]])

In [57]:
length0, length1 = a.shape
for i in range(length0):
    for j in range(length1):
        print(a[i][j], a[i, j])

1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
0 0
1 1
2 2


In [58]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [0, 1, 2]])
a[1: , 0:2]

array([[4, 5],
       [7, 8],
       [0, 1]])

In [61]:
a = np.array(
    [
        [1,2,3,4], 
        [5,6,7,8], 
        [9,10,11,12], 
        [13,14,15,16]
    ]
)

a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [62]:
a[ a % 2 == 0 ]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [65]:
arr = np.arange(1, 101)

multiples_of_3 = arr[arr % 3 == 0]

multiples_of_3


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [66]:
a = np.array([10, 20, 30])
a.max(), a.min()

(np.int64(30), np.int64(10))

In [67]:
a.mean()

np.float64(20.0)

In [68]:
a.astype(np.float64)

array([10., 20., 30.])

In [69]:
b = np.array([[1, 1], [2, 2], [3, 3]])
b.flatten()

array([1, 1, 2, 2, 3, 3])

In [ ]:
b = np.array([
    [1, 1], 
    [2, 2], 
    [3, 3]])
b.T

array([[1, 2, 3],
       [1, 2, 3]])

In [72]:
c = np.array([35, 24, 55, 69, 19, 99])
c.sort()
c[::-1] 

array([99, 69, 55, 35, 24, 19])

In [73]:
d = np.array(
    [
        [35, 24, 55], 
        [69, 19, 9], 
        [4, 1, 11]
    ]
)

d.sort()
d

array([[24, 35, 55],
       [ 9, 19, 69],
       [ 1,  4, 11]])

In [74]:
d = np.array(
    [
        [35, 24, 55], 
        [69, 19, 9], 
        [4, 1, 11]
    ]
)
d.sort(axis=0)
d

array([[ 4,  1,  9],
       [35, 19, 11],
       [69, 24, 55]])

In [75]:
a = np.array([1, 2, 3])
b = np.array([
    [4, 5, 6], 
    [7, 8, 9]
    ])
np.append(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.append([a], b, axis = 0) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
a = [1, 2, 3, 4, 5, 6, 7, 8]
b = np.reshape(a,(2,4)) 
c = np.reshape(a,(4,2))
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [79]:
a = np.arange(1,9)  
b = a.reshape(2,2,2)
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [80]:
b[0]

array([[1, 2],
       [3, 4]])

In [ ]:
a=np.arange(10).reshape(-1,5) 
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
a.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8]) 
a.reshape(-1,4) 
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
def pseudo_rand(x):
    a = 1103515245
    b = 12345
    m = 2 ** 31
    new_x = (a * x + b) % m
    return new_x

seed = 100 

x = pseudo_rand(seed)
print(x)

829870797


In [94]:
np.random.rand(5)

array([0.30194638, 0.82979069, 0.9309005 , 0.64797257, 0.61110858])

In [95]:
np.random.randint(150, 191, size=10)

array([178, 174, 176, 172, 172, 159, 158, 159, 185, 163])

In [106]:
rnd = np.random.randn(5) * 10 + 165
rnd

array([159.55617275, 166.1092259 , 153.49006423, 168.75698018,
       158.9936131 ])

In [97]:
rnd.round(2)

array([170.58, 167.72, 161.41, 168.94, 177.7 ])

In [98]:
rnd.astype(int)

array([170, 167, 161, 168, 177])

In [160]:
np.random.seed(42)
rand_nums = np.random.rand(5)
rand_nums

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [171]:
nums = np.random.normal(loc=165, scale=10, size=(3, 4)).round(2)
nums

array([[179.05, 178.92, 156.19, 165.77],
       [160.07, 174.23, 182.07, 173.74],
       [165.09, 161.34, 171.49, 152.77]])

In [172]:
import time

arr_a = np.random.rand(100)
arr_b = np.random.rand(100)
result = np.zeros(100)

In [175]:
start = time.time()
for i in range(len(arr_a)):
    result[i] = arr_a[i] * arr_b[i]
end = time.time()
print('소요시간: ', end - start)

소요시간:  8.106231689453125e-05


In [176]:
start = time.time()
result = arr_a * arr_b 
end = time.time()
print('소요시간: ', end - start)
print('소요시간: {:12.10f}'.format(end - start))

소요시간:  5.030632019042969e-05
소요시간: 0.0000503063


In [177]:
n_elem = 100000
arr_a = np.random.rand(n_elem)
arr_b = np.random.rand(n_elem)
result = np.zeros(n_elem)

In [178]:
start = time.time()
for i in range(n_elem):
    result[i] = arr_a[i] * arr_b[i]

end = time.time()
print('원소별 접근 방식 소요시간: ', end - start)

start = time.time()
result = arr_a * arr_b
end = time.time()
print('벡터화 연산 수행 소요시간: ', end - start)

원소별 접근 방식 소요시간:  0.0177309513092041
벡터화 연산 수행 소요시간:  0.00020766258239746094


In [ ]:
arr = np.array([[1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
               ])
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))
np.sum(arr, axis=(0, 1))

[ 5 10 15 20 25]
[15 15 15 15 15]


np.int64(75)

In [ ]:
import numpy as np
import time

n = 1000
arr = np.random.rand(n, n)

In [ ]:
sum_naive = 0
start = time.time()
for i in range(n):
    for j in range(n):
        sum_naive += arr[i,j]
end = time.time()
print(n, 'x', n, "배열의 원소 합", sum_naive, "\n계산 시간: ", end-start)

1000 x 1000 배열의 원소 합 500097.32126972114 
계산 시간:  0.1275920867919922


In [ ]:
start = time.time()
sum_reduction = np.sum(arr, axis = (0,1))
end = time.time()
print(n, 'x', n, "배열의 원소 합", sum_reduction,"\n계산 시간: ",end-start)

1000 x 1000 배열의 원소 합 500097.32126971683 
계산 시간:  0.00045800209045410156


## Linear Algebra (Solving Equations)

In [183]:
# solving for as = b
a = np.array([[1,2], [1,-3]])
b = np.array([6,1])
s = np.linalg.solve(a,b)
print(s)

[4. 1.]


In [184]:
a = np.array([[2,1], [4,5]])
det_a = np.linalg.det(a)
b = np.array([[1,2], [3,-6]])
det_b = np.linalg.det(b)
print(det_a, det_b)

6.0 -12.0


In [ ]:
import numpy as np

a = np.arange(10, 18).reshape(2,4)
a 

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [ ]:
b = np.arange(12).reshape(3,4)
b 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
c = np.arange(8).reshape(2,4)
c  

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
d = list(range(4))
d 

[0, 1, 2, 3]

In [190]:
np.concatenate((a, b))  

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [191]:
np.vstack((a, b))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [192]:
np.vstack((a, d))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3]])

In [193]:
np.vstack((a, b, d))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [194]:
np.hstack((a, c)) 

array([[10, 11, 12, 13,  0,  1,  2,  3],
       [14, 15, 16, 17,  4,  5,  6,  7]])

In [196]:
# a 배열은 형상이 (2, 4), b 배열은 (3, 4)로 수평 결합이 안됨
np.hstack((a, b)) # a 배열과 b 배열의 hstack 결합-오류

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [197]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("원본 배열:\n", arr)

# axis=0 (세로 방향, 행을 따라 열을 연산)
sum_axis0 = np.sum(arr, axis=0)
print("\naxis=0 연산 결과:", sum_axis0)  # 각 열을 따라 합산

# axis=1 (가로 방향, 열을 따라 행을 연산)
sum_axis1 = np.sum(arr, axis=1)
print("\naxis=1 연산 결과:", sum_axis1)  # 각 행을 따라 합산


원본 배열:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

axis=0 연산 결과: [12 15 18]

axis=1 연산 결과: [ 6 15 24]


In [198]:
arr_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("원본 3D 배열:\n", arr_3d)

# axis=0 (같은 위치에 있는 2D 배열끼리 연산)
sum_axis0 = np.sum(arr_3d, axis=0)
print("\naxis=0 연산 결과:\n", sum_axis0)

# axis=1 (2D 배열 내부에서 같은 행끼리 연산)
sum_axis1 = np.sum(arr_3d, axis=1)
print("\naxis=1 연산 결과:\n", sum_axis1)

# axis=2 (2D 배열 내부에서 같은 열끼리 연산)
sum_axis2 = np.sum(arr_3d, axis=2)
print("\naxis=2 연산 결과:\n", sum_axis2)


원본 3D 배열:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

axis=0 연산 결과:
 [[ 6  8]
 [10 12]]

axis=1 연산 결과:
 [[ 4  6]
 [12 14]]

axis=2 연산 결과:
 [[ 3  7]
 [11 15]]
