## mac의 m시리즈에서는 XGBoost 실행을 못시킴. 이 파일 실행시킬 때는 구글 colab 사용해서 진행하기.
## (240726 수업부터 앞으로 코랩으로 진행)

In [22]:
# %pip install xgboost==1.5.0
# %pip install pandas==1.5

In [23]:
import xgboost as xgb

print(xgb.__version__)

1.5.0


In [24]:
import warnings
warnings.filterwarnings('ignore')

# 코드 설명

# import warnings
# 이 줄은 파이썬의 표준 라이브러리 중 하나인 warnings 모듈을 가져옵니다.
# warnings 모듈은 코드 실행 중에 발생할 수 있는 경고 메시지를 제어할 수 있게 해줍니다.
# 경고 메시지는 코드의 잠재적인 문제를 알려주지만, 프로그램의 실행을 중단시키지는 않습니다.
# 예를 들어, deprecated(사용 중단 예정)된 함수나 라이브러리를 사용할 때 경고 메시지가 출력될 수 있습니다.

# warnings.filterwarnings('ignore')
# 이 줄은 warnings 모듈의 filterwarnings 함수를 사용하여 특정 유형의 경고 메시지를 무시하도록 설정합니다.
# 여기서 'ignore'는 경고 메시지를 무시하도록 설정하는 명령어입니다.

# 왜 사용하나요?

# 깨끗한 출력: 경고 메시지를 무시함으로써 프로그램 실행 중에 출력되는 불필요한 메시지를 제거하여, 출력 결과를 더 깔끔하게 볼 수 있습니다.
# 불필요한 경고 무시: 특정 경고가 중요하지 않거나 이미 알고 있는 경우, 해당 경고를 무시함으로써 코드 실행에 방해가 되지 않게 할 수 있습니다.

# 언제 사용하나요?

# Deprecated 경고 무시: 오래된 라이브러리나 함수 사용 시 발생하는 경고를 무시하고 싶을 때.
# 테스트 코드: 테스트 코드에서 경고 메시지가 많을 경우, 경고를 무시하고 싶을 때.
# 일시적 해결: 특정 경고를 일시적으로 무시하고 나중에 해결하고자 할 때.

# 주의사항

# 중요 경고 무시 주의: 모든 경고를 무시하면 중요한 문제를 놓칠 수 있습니다. 꼭 필요한 경우에만 사용하세요.
# 코드 리뷰: 팀 프로젝트에서 코드를 작성할 때는 다른 팀원과 상의하여 경고 무시 설정을 사용하세요. 경고를 무시하는 것이 좋은 해결책인지 판단이 필요합니다.


In [25]:
from sklearn.datasets import load_breast_cancer
import pandas as pd

cancer = load_breast_cancer()

data_df = pd.DataFrame(cancer.data, columns=cancer.feature_names)
data_df['target'] = cancer.target
data_df.head()




# load_breast_cancer: 사이킷런의 데이터셋 모듈에서 유방암 데이터셋을 가져오는 함수입니다.
# pandas as pd: 판다스 라이브러리를 pd라는 별칭으로 가져옵니다. 판다스는 데이터 조작과 분석을 위한 강력한 라이브러리입니다.

# load_breast_cancer() 함수를 사용하여 유방암 데이터셋을 로드합니다. 이 함수는 사이킷런의 내장 데이터셋 중 하나인 유방암 데이터를 반환합니다.

# cancer.data: 유방암 데이터셋의 특성(feature) 데이터를 포함합니다. 각 행은 하나의 데이터 포인트를 나타내며, 각 열은 하나의 특성을 나타냅니다.
# cancer.feature_names: 특성의 이름을 포함하는 리스트입니다.
# pd.DataFrame(): 특성 데이터를 포함하는 판다스 데이터프레임을 생성합니다. columns 매개변수를 사용하여 데이터프레임의 열 이름을 설정합니다.

# cancer.target: 각 데이터 포인트의 레이블(0 또는 1)을 포함합니다. 0은 악성 종양, 1은 양성 종양을 나타냅니다.
# data_df['target']: 데이터프레임에 'target'이라는 새로운 열을 추가하고, 각 데이터 포인트의 레이블을 할당합니다.

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [26]:
from sklearn.model_selection import train_test_split

# 데이터셋을 학습 세트와 테스트 세트로 분할
X_train, X_test, y_train, y_test = train_test_split(
    data_df.drop("target", axis=1),  # 입력 데이터 (특성들)
    data_df['target'],               # 출력 데이터 (레이블)
    random_state=42                  # 무작위 분할을 위한 시드 값
)

# 학습 세트를 다시 학습 세트와 검증 세트로 분할
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train,                         # 학습 데이터 (특성들)
    y_train,                         # 학습 데이터 (레이블)
    random_state=42                  # 무작위 분할을 위한 시드 값
)

# 코드의 역할 요약

# 1. 데이터셋을 학습 세트와 테스트 세트로 분할

# data_df에서 'target' 열을 제외한 데이터(특성들)를 X_train과 X_test로 분할.
# data_df['target']을 y_train과 y_test로 분할.
# random_state=42: 무작위 분할을 재현 가능하게 하기 위해 시드 값 설정.

# 2. 학습 세트를 다시 학습 세트와 검증 세트로 분할

# X_train을 다시 X_train과 X_valid로 분할.
# y_train을 다시 y_train과 y_valid로 분할.
# random_state=42: 무작위 분할을 재현 가능하게 하기 위해 시드 값 설정.

# 요약

# X_train, y_train: 모델 학습에 사용되는 데이터.
# X_valid, y_valid: 모델 검증에 사용되는 데이터.
# X_test, y_test: 최종 모델 평가에 사용되는 데이터.
# 이렇게 데이터를 나누면 학습, 검증, 테스트 단계에서 각각 다른 데이터 세트를 사용할 수 있어 모델의 성능을 보다 정확하게 평가할 수 있습니다.


# DMatrix 변환
- 넘파이 배열, 판다스 데이터 프레임을 DMatrix로 변환

In [27]:
import pandas as pd

pd.__version__

'1.5.0'

In [28]:
# 학습, 검증, 테스트 데이터를 DMatrix 객체로 변환
dtr = xgb.DMatrix(data=X_train, label=y_train)
dval = xgb.DMatrix(data=X_valid, label=y_valid)
dtest = xgb.DMatrix(data=X_test, label=y_test)

# 이 코드는 XGBoost의 DMatrix 객체를 생성하는 예제입니다.
# DMatrix는 XGBoost의 데이터 구조로, 학습, 검증 및 테스트 데이터를 효율적으로 관리하고 처리할 수 있게 해줍니다.


# 1. DMatrix 객체 생성

# X_train: 학습 데이터의 특성(features)을 나타냅니다.
# y_train: 학습 데이터의 레이블(labels)을 나타냅니다.
# xgb.DMatrix: XGBoost의 DMatrix 객체를 생성하는 함수입니다. 이 객체는 내부적으로 데이터와 레이블을 효율적으로 저장하고 처리할 수 있도록 합니다.
# dtr: 학습 데이터를 위한 DMatrix 객체입니다.

# 2. 검증 데이터에 대한 DMatrix 객체 생성
# X_valid: 검증 데이터의 특성(features)을 나타냅니다.
# y_valid: 검증 데이터의 레이블(labels)을 나타냅니다.
# dval: 검증 데이터를 위한 DMatrix 객체입니다.

# 3. 테스트 데이터에 대한 DMatrix 객체 생성

# X_test: 테스트 데이터의 특성(features)을 나타냅니다.
# y_test: 테스트 데이터의 레이블(labels)을 나타냅니다.
# dtest: 테스트 데이터를 위한 DMatrix 객체입니다.

# 요약

# DMatrix: XGBoost에서 데이터를 효율적으로 관리하고 처리하기 위해 사용하는 데이터 구조입니다.

# dtr: 학습 데이터를 위한 DMatrix 객체.
# dval: 검증 데이터를 위한 DMatrix 객체.
# dtest: 테스트 데이터를 위한 DMatrix 객체.

# 이렇게 데이터를 DMatrix 객체로 변환하면, XGBoost 모델을 학습하고 평가할 때 데이터를 보다 효율적으로 사용할 수 있습니다.
# DMatrix는 특히 대용량 데이터셋을 처리할 때 메모리 사용량을 최적화하고, 학습 속도를 향상시키는 데 도움이 됩니다.


# XGB 하이퍼 파라미터 설정

In [31]:
params = {
    "max_depth": 3,
    'eta': 0.05,
    'objective': 'binary:logistic',
    'eval_metric': 'logloss'
}

# 최대 400회 훈련
num_rounds = 400


# 이 코드는 XGBoost 모델의 하이퍼파라미터를 설정하고, 모델 훈련을 최대 400회 반복하도록 지정합니다.

# max_depth: 각 결정 트리의 최대 깊이를 지정합니다. 깊이가 깊을수록 모델이 더 복잡해지고 과적합될 가능성이 높아집니다. 여기서는 3으로 설정하여 과적합을 방지합니다.
# eta: 학습률(learning rate)로, 각 단계에서 모델이 업데이트되는 정도를 제어합니다. 값이 작을수록 학습 속도가 느리지만 더 세밀하게 조정할 수 있습니다. 여기서는 0.05로 설정되었습니다.
# objective: 학습의 목적을 정의합니다. 'binary'은 이진 분류 문제를 의미하며, 로지스틱 회귀를 사용합니다.
# eval_metric: 평가 지표를 설정합니다. 'logloss'는 로그 손실(logarithmic loss)로, 예측의 불확실성을 측정하는 데 사용됩니다.



# 훈련

In [33]:
eval_list = [
    (dtr, 'train'),
    (dval, 'eval')
]

xgb_model = xgb.train(
    params=params, # 하이퍼 파라미터
    dtrain=dtr,
    num_boost_round=num_rounds, # 최대 학습 횟수
    early_stopping_rounds=50, # 성능 개선이 50 라운드 이내에 이루어지지 않으면 학습 중단
    evals=eval_list # 평가 세트 지정
)

[0]	train-logloss:0.62706	eval-logloss:0.60229
[1]	train-logloss:0.59030	eval-logloss:0.57112
[2]	train-logloss:0.55534	eval-logloss:0.54548
[3]	train-logloss:0.52351	eval-logloss:0.52160
[4]	train-logloss:0.49440	eval-logloss:0.50040
[5]	train-logloss:0.46768	eval-logloss:0.48104
[6]	train-logloss:0.44391	eval-logloss:0.45909
[7]	train-logloss:0.42107	eval-logloss:0.44270
[8]	train-logloss:0.39994	eval-logloss:0.42712
[9]	train-logloss:0.38036	eval-logloss:0.41490
[10]	train-logloss:0.36265	eval-logloss:0.40124
[11]	train-logloss:0.34564	eval-logloss:0.39045
[12]	train-logloss:0.32978	eval-logloss:0.38058
[13]	train-logloss:0.31499	eval-logloss:0.37156
[14]	train-logloss:0.30116	eval-logloss:0.36372
[15]	train-logloss:0.28823	eval-logloss:0.35494
[16]	train-logloss:0.27603	eval-logloss:0.34791
[17]	train-logloss:0.26459	eval-logloss:0.34123
[18]	train-logloss:0.25401	eval-logloss:0.33128
[19]	train-logloss:0.24382	eval-logloss:0.32515
[20]	train-logloss:0.23430	eval-logloss:0.31550
[2

KeyError: 'num_parallel_tree'

In [ ]:
import numpy as np

pred_props = xgb_model.predict(dtest)
pred_props[:10] # 양성 클래스의 확률

NameError: name 'xgb_model' is not defined

In [ ]:
threshold = 0.5

preds = [1 if x > threshold else 0 for x in pred_props ]
preds[:10]

[1, 0, 0, 1, 1, 0, 0, 1, 0, 1]

# XGBoost - Scikit Learn Wrapper

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgb_clf = XGBClassifier(
    n_estimators=400, # 학습 횟수
    learning_rate = 0.05, # 학습률(eta)
    max_depth=3,
    eval_metric='logloss'
)

xgb_clf.fit(X_train, y_train, verbose=True)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=400,
              n_jobs=None, num_parallel_tree=None, random_state=None, ...)

In [ ]:
preds = xgb_clf.predict(X_test)
preds[:10]

array([1, 0, 0, 1, 1, 0, 0, 1, 0, 1])

In [ ]:
pred_proba = xgb_clf.predict_proba(X_test)
pred_proba[:10]

array([[7.3437452e-02, 9.2656255e-01],
       [9.9860471e-01, 1.3952850e-03],
       [9.9924982e-01, 7.5019279e-04],
       [1.5795231e-03, 9.9842048e-01],
       [2.6434660e-04, 9.9973565e-01],
       [9.9915171e-01, 8.4831589e-04],
       [9.9709845e-01, 2.9015488e-03],
       [3.3829182e-01, 6.6170818e-01],
       [5.5896002e-01, 4.4103998e-01],
       [3.5931468e-03, 9.9640685e-01]], dtype=float32)

In [ ]:
# Early Stopping 적용
xgb_clf = XGBClassifier(
    n_estimators=400,
    learning_rate=0.05,
    max_depth=3
)

In [ ]:
evals = [
    (X_train, y_train),
    (X_valid, y_valid)
]

xgb_clf.fit(
    X_train, y_train,
    early_stopping_rounds = 50,
    eval_set=evals,
    verbose=True
)

[0]	validation_0-logloss:0.62706	validation_1-logloss:0.60229
[1]	validation_0-logloss:0.59030	validation_1-logloss:0.57112
[2]	validation_0-logloss:0.55534	validation_1-logloss:0.54548
[3]	validation_0-logloss:0.52351	validation_1-logloss:0.52160
[4]	validation_0-logloss:0.49440	validation_1-logloss:0.50040
[5]	validation_0-logloss:0.46768	validation_1-logloss:0.48104
[6]	validation_0-logloss:0.44391	validation_1-logloss:0.45909
[7]	validation_0-logloss:0.42107	validation_1-logloss:0.44270
[8]	validation_0-logloss:0.39994	validation_1-logloss:0.42712
[9]	validation_0-logloss:0.38036	validation_1-logloss:0.41490
[10]	validation_0-logloss:0.36265	validation_1-logloss:0.40124
[11]	validation_0-logloss:0.34564	validation_1-logloss:0.39045
[12]	validation_0-logloss:0.32978	validation_1-logloss:0.38058
[13]	validation_0-logloss:0.31499	validation_1-logloss:0.37156
[14]	validation_0-logloss:0.30116	validation_1-logloss:0.36372
[15]	validation_0-logloss:0.28823	validation_1-logloss:0.35494
[1

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=400, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [ ]:
# Feature 중요도 확인
xgb_clf.feature_importances_

array([0.01235224, 0.01258327, 0.00553193, 0.01693648, 0.00369544,
       0.00555813, 0.01183528, 0.24660403, 0.00128275, 0.00869971,
       0.01515575, 0.00208906, 0.01706614, 0.01396721, 0.00518284,
       0.00460533, 0.00378786, 0.00211838, 0.00248873, 0.00207492,
       0.04405012, 0.04099744, 0.22401944, 0.08619169, 0.00919142,
       0.00310335, 0.01205984, 0.18114622, 0.00401972, 0.00160521],
      dtype=float32)